name: Call a reusable workflow and use its outputs

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: WorkshopOrgTest/newdemo/.github/workflows/wctest.yml@main
    with:
      username: mona
